name:                lmdb-resource
version:             0.1.0.0
github:              "shlok/lmdb-resource"
license:             BSD3
author:              "Shlok Datye"
maintainer:          "shlok@quant.is"
copyright:           "2019 Shlok Datye"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Work with an LMDB database within a MonadResource.
category:            Data, Database

description:         Please see the README on GitHub at <https://github.com/shlok/lmdb-resource#readme>

dependencies:
- async
- base >= 4.7 && < 5
- bytestring
- lmdb
- mtl
- resourcet
- unliftio

ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  lmdb-resource-test:
    main:                TestSuite.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory
    - lmdb-resource
    - QuickCheck
    - tasty
    - tasty-quickcheck
    - temporary
